vich_uploader:
    db_driver: orm

    mappings:
        figure_image:
            uri_prefix: /img/figure
            upload_destination: '%kernel.project_dir%/public/img/figure'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
